### ISSUE TITLE
我帮你部署

### ISSUE THREAD

**Issue by awong1900** [HelTi/todo-done#1]
vx：awong1900

**Comment by HelTi** [comment]
> vx：awong1900

您好，可以的，好久没看到～

**Comment by awong1900** [comment]
没事，还需要吗

**Comment by HelTi** [comment]
> 没事，还需要吗

如果您那边方便可以部署～，代码都是开源的

**Comment by awong1900** [comment]
OK

**Comment by HelTi** [comment]
> OK。 不过我暂时没有时间。上次论坛看到你说没有认证账号，我可以做到给你开一个小程序账号，你自己部署。

那好～你可以发我邮箱 helti@qq.com

**Comment by awong1900** [comment]
ok

**Comment by awong1900** [comment]
激活邮件发到你邮箱了。
